name: Deploy to Firebase Hosting on merge

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --legacy-peer-deps

      - name: Build (Angular prod)
        run: npm run build -- --configuration production

      - name: Debug dist (ver onde saiu o index.html)
        run: |
          echo "== dist ==" && ls -la dist || true
          echo "== dist/stockx ==" && ls -la dist/stockx || true
          echo "== dist/stockx/browser ==" && ls -la dist/stockx/browser || true
          echo "== dist/crud-pi ==" && ls -la dist/crud-pi || true

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STOCKX_BBAC4 }}'
          channelId: live
          projectId: stockx-bbac4
